### PR TITLE
Contribute Readme

### PR DESCRIPTION
**Pull request by SHASHANK-PRO-05**
I have written a document that can help developers in getting started with Prisma Development. Let me know the changes.

### CODE REVIEW

**Comment by do4gr** [comment]
Hey, thanks for writing this up. We'll think about where to put this and what else we would want in a guide to Core contributions. 

As for setting up tests, you can have a look at the PaginationSpec, there we set up the test schema straight from a GraphQL SDL. The other way you described is a holdover from when those older tests like JsonVariablesSpec were created and we did not have a way to set them up using SDL yet. I think starting with SDL should make writing tests a lot easier for contributors. We just did not have time to switch the old tests over to the new format.

**Comment by SHASHANK-PRO-05** [comment]
Cool. I will work on it.

**Comment by SHASHANK-PRO-05** [comment]
@do4gr I have updated the Tutorial. Also, to be consistent with the tutorial I have updated JsonVariableSpec SDL.

**Comment by mavilein** [comment]
@SHASHANK-PRO-05 : Hey, thanks for this amazing contribution! 🙏 Can you rebase your branch onto our latest `alpha` branch? Right now there are lots of merge conflicts and therefore i can't merge.

**Comment by SHASHANK-PRO-05** [comment]
@mavilein Thanks for reviewing it. I have moved this pull request to #2785 because rebase was not happening automatically even with `recursive theirs` strategy. Some internal work was involved which I have no clue about so it would be better to move to a different and clean pull request.  Thanks :)

**Pull request closed without merging**
